# ğŸš€ GitHub Snake Animation

permissions:
  contents: write

name: ğŸ Snake Animation

on:
  schedule: 
    - cron: "0 0 * * *" # executa todo dia Ã  meia-noite (UTC)
  workflow_dispatch: # permite rodar manualmente

permissions:
  contents: write # permite que o bot faÃ§a commit na branch de saÃ­da

jobs:
  build:
    name: Generating and Publishing the Snake
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

     - name: Generating Snake animation
       uses: Platane/snk/svg-only@v3
       with:
       github_user_name: LucianoAle-FS
       outputs: dist/github-contribution-grid-snake.svg

      - name: publishing branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
